### ISSUE TITLE
Manga Not Found Error

### ISSUE THREAD

**Issue by xgorn** [krypton-byte/komiku#1]
IndexError, it didn't fetch any manga tho the manga are available in komiku

**Comment by krypton-byte** [comment]
can you send your code

**Comment by xgorn** [comment]
▶ Code : 
from komiku import searchManga
dow=searchManga("naruto").fetch[1]
down=dow.download()
down.save(f"{dow.title}.pdf") 

▶ Output / TraceBack : 
Traceback (most recent call last):
  File "/plugins/code_runner.py", line 96, in eval
    await aexec(cmd, client, message)
  File "/plugins/code_runner.py", line 125, in aexec
    return await locals()["__aexec"](client, message)
  File "<string>", line 3, in __aexec
IndexError: list index out of range

**Comment by X-Gorn** [comment]
▶ Code : 
from komiku import searchManga
dow=searchManga("naruto").fetch[1]
down=dow.download()
down.save(f"{dow.title}.pdf") 

▶ Output / TraceBack : 
Traceback (most recent call last):
  File "/plugins/code_runner.py", line 96, in eval
    await aexec(cmd, client, message)
  File "/plugins/code_runner.py", line 125, in aexec
    return await locals()["__aexec"](client, message)
  File "<string>", line 3, in __aexec
IndexError: list index out of range
